### ISSUE TITLE
Insert chart in existing xlsx file

### ISSUE THREAD

**Issue by mikaoelitiana** [objectum/xlsx-chart#1]
Hello,
I wanted to know if it is possible to use this to output chart to be integrated in another xlsx for report. 
We have an existing report generated automatically and want to integrate chart along with other informations. How can we do that using xlsx-chart.
Thanks

**Comment by objectum** [comment]
Hello,
xlsx-chart builds charts using templates from directory xlsx-chart/template.
It's not possible now because need function of copying chart from one file to another.

**Comment by Summer0405** [comment]
@mikaoelitiana ,
I have same problem with you on generating chart,could you tell me how you solved it?
Thanks

**Comment by mikaoelitiana** [comment]
@Summer0405 We finally didn't implement the feature as it was not easy enough at that time.

**Comment by Summer0405** [comment]
@mikaoelitiana ok,thanks.
